name: Github Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          envkey_NASA_API_URL: ${{ secrets.NASA_API_URL }}
      - uses: subosito/flutter-action@v2.16.0
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /nasa-apod/
          webRenderer: html
